#!/bin/sh
#SBATCH -N 1

# Append job id to 'preTextInResultFile'
original_line=`cat /share/earza/evolutionary_robotics_framework/experiments/$1/parameters.csv | grep "preTextInResultFile" `
original_param=`python3 -c "a='$original_line';b=a.split(',')[-1];print(b)"`
python3 scripts/utils/UpdateParameter.py -f /share/earza/evolutionary_robotics_framework/experiments/$1/parameters.csv -n preTextInResultFile -v ${original_param}_job_${SLURM_JOB_ID}



python3 /share/earza/evolutionary_robotics_framework/simulation/Cluster/run_cluster.py --xvfb 1 --params /share/earza/evolutionary_robotics_framework/experiments/$1/parameters.csv --client /share/earza/library/bin/are-client --vrep /share/earza/CoppeliaSim_Edu_V4_3_0_Ubuntu18_04/coppeliaSim.sh --port-start $2 $3
sleep 2
rm -r /share/earza/evolutionary_robotics_framework/experiments/$1