#!/bin/sh
#SBATCH -N 1
#SBATCH --time=5-00:00:00 #Walltime

# Append job id to 'preTextInResultFile'
original_line=`cat /share/earza/evolutionary_robotics_framework/experiments/$1/parameters.csv | grep "preTextInResultFile" `
original_param=`python3 -c "a='$original_line';b=a.split(',')[-1];print(b)"`
python3 scripts/utils/UpdateParameter.py -f /share/earza/evolutionary_robotics_framework/experiments/$1/parameters.csv -n preTextInResultFile -v ${original_param}_job_${SLURM_JOB_ID}

xvfb-run --auto-servernum --server-num=1 /share/earza/CoppeliaSim_Edu_V4_3_0_Ubuntu18_04/coppeliaSim.sh -h -g/share/earza/evolutionary_robotics_framework/experiments/$1/parameters.csv

sleep 2
rm -r /share/earza/evolutionary_robotics_framework/experiments/$1